#!/bin/bash

input_file="$1"
if [ -z "$input_file" ]; then
  echo "Usage: $0 <input_file>"
  exit 1
fi
curl -X POST http://localhost:8080/edge/create_user \
     -H "Content-Type: application/json" \
     -d @"${input_file}" | jq 
